### Date: 17/03/2023
### Regd No: 22231
### Name: K Lalith Aditya
### MDSC-202(P) - Multivaraite Statistical Analysis
### R Lab 2

### Matrix Multiplication using operand

In [33]:
x <- matrix(nrow=4, ncol=2, data=1:8,byrow=TRUE)
x

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6   
[4,] 7    8

### Transpose of a Matrix with product to Normal Matrix

In [34]:
xtx <- t(x) %*% x
xtx

[,1] [,2]
[1,]  84  100 
[2,] 100  120

In [37]:
## crossproduct(Transpose(x)*x)
xtx2 <- crossprod(x)
xtx2

[,1] [,2]
[1,]  84  100 
[2,] 100  120

### scalar multiplication to a matrix

In [41]:
.2356*x

[,1]   [,2]  
[1,] 0.2356 0.4712
[2,] 0.7068 0.9424
[3,] 1.1780 1.4136
[4,] 1.6492 1.8848

### Some Linear Combinations

In [42]:
# 1.

3.4*x - 1.2*x

[,1] [,2]
[1,]  2.2  4.4
[2,]  6.6  8.8
[3,] 11.0 13.2
[4,] 15.4 17.6

In [43]:
# 2.
5*x + 4*x

[,1] [,2]
[1,]  9   18  
[2,] 27   36  
[3,] 45   54  
[4,] 63   72

In [44]:
# 3.
2*x + 21*x + 3*x - 4*x

[,1] [,2]
[1,]  22   44 
[2,]  66   88 
[3,] 110  132 
[4,] 154  176

### Using solve() to find inverse of a matrix

In [53]:
y <- matrix(nrow=3 , ncol=3,byrow=T,data=c(1,2,3,3,4,5,4,5,1))

In [54]:
y

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 3    4    5   
[3,] 4    5    1

In [55]:
solve(y)

[,1] [,2] [,3]
[1,] -2.1  1.3 -0.2
[2,]  1.7 -1.1  0.4
[3,] -0.1  0.3 -0.2

### Getting identity matrix back 

In [56]:
y %*% solve(y)

[,1]          [,2]         [,3]         
[1,]  1.000000e+00 0.000000e+00 -1.110223e-16
[2,] -8.326673e-16 1.000000e+00  1.110223e-16
[3,] -3.469447e-16 1.665335e-16  1.000000e+00

### The non diagonal entries are close to 0(very small)

## Finding Eigen values and Eigen Vectors of a Matrix!

In [57]:
eigen(y)

eigen() decomposition
$values
[1]  9.6360956 -3.3238808 -0.3122148

$vectors
           [,1]       [,2]        [,3]
[1,] -0.3707376 -0.3861027 -0.76622760
[2,] -0.7189333 -0.4069940  0.63636323
[3,] -0.5879528  0.8278167 -0.08909043
