### Date: 17/02/2023
### Regd No: 22231
### Name: K Lalith Aditya
### MDSC-202(P) - Multivaraite Statistical Analysis
### R Lab


### Matrix Structure

In [35]:
A <- matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=2+1)
A

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

### Arrangement by Row

In [36]:
B <- matrix(data=c(9,8,7,6,5,4,3,2),nrow=2,ncol=4,byrow=TRUE)
B

[,1] [,2] [,3] [,4]
[1,] 9    8    7    6   
[2,] 5    4    3    2

### Arrangement by Column

In [37]:
B <- matrix(data=c(9,8,7,6,5,4),nrow=3,ncol=2,byrow=FALSE)
B

[,1] [,2]
[1,] 9    6   
[2,] 8    5   
[3,] 7    4

### rbind and cbind

In [38]:
rb<- rbind(-1:3,-4:0)
rb

[,1] [,2] [,3] [,4] [,5]
[1,] -1    0    1    2   3   
[2,] -4   -3   -2   -1   0

In [39]:
cb<- cbind(-2:2,-2:2)
cb

[,1] [,2]
[1,] -2   -2  
[2,] -1   -1  
[3,]  0    0  
[4,]  1    1  
[5,]  2    2

In [40]:
A <-matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=3)
A

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

### Dimension

In [41]:
dim(A)

[1] 2 3

In [42]:
dim(A)[2]

[1] 3

### No of rows

In [43]:
nrow(A)

[1] 2

### No of columns

In [44]:
ncol(A)

[1] 3

### Extracting elements from a Matrix

In [45]:
A <- matrix(c(.1,.2,.3,.4,.5,.6,.7,.8,.9,1,1.1,1.2,1.3,1.4,1.5,1.6),nrow=4,ncol=4)
A

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 0.3  0.7  1.1  1.5 
[4,] 0.4  0.8  1.2  1.6

#### 1.Diagonal elements of a Matrix

In [46]:
diag(x=A)

[1] 0.1 0.6 1.1 1.6

#### 2. Element of 3rd row and 2nd column

In [47]:
A[3,2]

[1] 0.7

#### 3. Elements of 2nd column

In [48]:
#3)
A[,2]

[1] 0.5 0.6 0.7 0.8

#### 4. Extracting 2nd and 3rd rows

In [49]:
A[2:3,]

[,1] [,2] [,3] [,4]
[1,] 0.2  0.6  1.0  1.4 
[2,] 0.3  0.7  1.1  1.5

#### 5. Extracting 4th and 2nd column

In [50]:
A[,c(4,2)]

[,1] [,2]
[1,] 1.3  0.5 
[2,] 1.4  0.6 
[3,] 1.5  0.7 
[4,] 1.6  0.8

#### 6. Extracting (4,2) ,(4,3) , (3,2) and (3,3) values

In [51]:
A[c(4,3),2:3]

[,1] [,2]
[1,] 0.8  1.2 
[2,] 0.7  1.1

### Manipulating a Matrix

In [52]:
A <- matrix(c(.1,.2,.3,.4,.5,.6,.7,.8,.9,1,1.1,1.2,1.3,1.4,1.5,1.6),nrow=4,ncol=4)
A

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 0.3  0.7  1.1  1.5 
[4,] 0.4  0.8  1.2  1.6

#### Removing column 2 from the matrix

In [53]:
A[,-2]

[,1] [,2] [,3]
[1,] 0.1  0.9  1.3 
[2,] 0.2  1.0  1.4 
[3,] 0.3  1.1  1.5 
[4,] 0.4  1.2  1.6

#### Removing row 4 and selecting column 3,2 and 1 in this order

In [54]:
A[-4,3:1]

[,1] [,2] [,3]
[1,] 0.9  0.5  0.1 
[2,] 1.0  0.6  0.2 
[3,] 1.1  0.7  0.3

#### Removing row 2 and column 3

In [55]:
A[-2,-3]

[,1] [,2] [,3]
[1,] 0.1  0.5  1.3 
[2,] 0.3  0.7  1.5 
[3,] 0.4  0.8  1.6

#### Removing row 2 and columns 3 and 4

In [56]:
A[-2,-c(3,4)]

[,1] [,2]
[1,] 0.1  0.5 
[2,] 0.3  0.7 
[3,] 0.4  0.8

#### Copying A into B

In [57]:
B<-A
B

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 0.3  0.7  1.1  1.5 
[4,] 0.4  0.8  1.2  1.6

#### Replacing 3rd row of B  with integers 1,2,3 and 4    

In [58]:
B[3,]<- 1:4
B

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 1.0  2.0  3.0  4.0 
[4,] 0.4  0.8  1.2  1.6

#### Replacing elements in (row 3,column 3) and (row 4,column 3) with value 100


In [25]:
B[c(3,4),3]<-100
B

[,1] [,2] [,3]  [,4]
[1,] 0.1  0.5    0.9 1.3 
[2,] 0.2  0.6    1.0 1.4 
[3,] 1.0  2.0  100.0 4.0 
[4,] 0.4  0.8  100.0 1.6

#### Replacing a Matrix's row with its column

##### Before changing

In [59]:
B

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 1.0  2.0  3.0  4.0 
[4,] 0.4  0.8  1.2  1.6

##### After changing

In [60]:
B<-A
B[4,]<-B[,4]
B

[,1] [,2] [,3] [,4]
[1,] 0.1  0.5  0.9  1.3 
[2,] 0.2  0.6  1.0  1.4 
[3,] 0.3  0.7  1.1  1.5 
[4,] 1.3  1.4  1.5  1.6

#### Changing matrix elements with vector

In [61]:
B[c(1,4),2:1]<-c(-100,100,-600,600)
B

[,1]   [,2]   [,3] [,4]
[1,] -600.0 -100.0 0.9  1.3 
[2,]    0.2    0.6 1.0  1.4 
[3,]    0.3    0.7 1.1  1.5 
[4,]  600.0  100.0 1.5  1.6

In [63]:
B[c(1,4),c(1,4)]<-c(-20,20)
B

[,1]  [,2]   [,3] [,4] 
[1,] -20.0 -100.0 0.9  -20.0
[2,]   0.2    0.6 1.0    1.4
[3,]   0.3    0.7 1.1    1.5
[4,]  20.0  100.0 1.5   20.0

#### Filling Diagonal elements of B with -99 

In [65]:
diag(B)<-rep(x=-99,times=4)
B

[,1]  [,2]   [,3]  [,4] 
[1,] -99.0 -100.0   0.9 -20.0
[2,]   0.2  -99.0   1.0   1.4
[3,]   0.3    0.7 -99.0   1.5
[4,]  20.0  100.0   1.5 -99.0